
service mariadb start

CRT_DB="CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
CRT_USR="CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
GRT_PRV="GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
ALT_USER="ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';"
FLSH="FLUSH PRIVILEGES;"

echo $CRT_DB$CRT_USR$GRT_PRV$ALT_USER$FLSH > database-creation.sql

mariadb -u root -p${MYSQL_ROOT_PASSWORD}  < database-creation.sql
